import { StyleSheet } from "react-native";

const cart = StyleSheet.create({
    container: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        width: "100%",
        height: "100%",
    },
    headerText: {
        fontSize: 22,
        fontWeight: "bold",
    },
    backBtn: {
        backgroundColor: "white",
        borderColor: "black",
        borderWidth: 2,
        borderRadius: 2,
        padding: "3%",
        boxShadow: "4px 5px rgba(0, 0, 0)",
    },
    cartSummary: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#7DF9FF",
        borderWidth: 2,
        borderColor: "black",
        padding: "4%",
        marginBottom: 12,
        boxShadow: "4px 5px rgba(0, 0, 0)",
    },
    itemsList: {
        flex: 1,
    },
    itemsListContent: {
        paddingBottom: 12,
        paddingRight: 4,
    },
    itemListCard: {
        backgroundColor: "white",
        borderColor: "black",
        borderWidth: 2,
        borderRadius: 2,
        boxShadow: "4px 5px rgba(0, 0, 0)",
        marginBottom: 12,
        marginEnd: 4,
        position: "relative",
    },
    itemImage: {
        width: "100%",
        height: 200,
    },
    itemOverview: {
        marginTop: 5,
        position: "absolute",
        width: "70%",
        height: "80%",
        zIndex: 2,
        padding: 10,
        gap: 6,
        display: "flex",
        experimental_backgroundImage: "linear-gradient(to right, rgb(191, 190, 190), rgba(0,0,0,0))",
    },
    itemName: {
        color: "white",
        fontWeight: "900",
        fontSize: 30,
    },
    itemPrice: {
        color: "white",
        fontSize: 25,
    },
    veg: {
        backgroundColor: "white",
        borderWidth: 2,
        borderRadius: 2,
        alignSelf: "flex-start",
        paddingVertical: 4,
        paddingHorizontal: 8,
        flexDirection: "row",
        alignItems: "center",
    },
    cardButtonsView: {
        flexDirection: "row",
        borderTopWidth: 2,
        borderColor: "black",
        alignItems: "stretch",
    },
    quantityView: {
        flexDirection: "row",
        flex: 2,
        alignItems: "stretch",
    },
    cardCountBtn: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        borderRightWidth: 2,
        borderColor: "black",
        paddingVertical: 12,
    },
    buttonText: {
        color: "black",
        fontWeight: "bold",
        fontSize: 16,
    },
    quantityDisplay: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 4,
    },
    subtotalView: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 8,
    },
    subtotalText: {
        fontSize: 18,
        fontWeight: "bold",
    },
    emptyCart: {
        backgroundColor: "white",
        borderColor: "black",
        borderWidth: 2,
        padding: 20,
        alignItems: "center",
        gap: 16,
        boxShadow: "4px 5px rgba(0, 0, 0)",
    },
    emptyCartText: {
        fontSize: 20,
        fontWeight: "bold",
    },
    shopBtn: {
        backgroundColor: "#7DF9FF",
        borderWidth: 2,
        borderColor: "black",
        padding: 12,
    },
    checkoutView: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "white",
        borderWidth: 2,
        borderColor: "black",
        padding: 12,
        marginTop: 8,
        marginBottom: 4,
        boxShadow: "4px 5px rgba(0, 0, 0)",
    },
    totalPrice: {
        fontSize: 24,
        fontWeight: "900",
    },
    checkoutBtn: {
        backgroundColor: "#2FFF2F",
        borderWidth: 2,
        borderColor: "black",
        padding: 14,
        boxShadow: "3px 4px rgba(0, 0, 0)",
    },
    checkoutBtnText: {
        color: "black",
        fontWeight: "bold",
        fontSize: 16,
    },
});

export default cart;
